---
- name: "unbound | Assert that ansible facts gathered successfully"
  ansible.builtin.assert:
    that:
      - "hostvars[inventory_hostname]['ansible_facts']['service_mgr'] is
        defined"
    fail_msg: "'ansible_facts' not found. Please enable facts gathering"
    quiet: "true"
- name: "unbound | Assert that system manager is systemd"
  ansible.builtin.assert:
    that:
      - "hostvars[inventory_hostname]['ansible_facts']['service_mgr'] ==
        'systemd'"
    fail_msg: "System manager is not systemd"
    quiet: "true"
- name: "unbound | Add the OS specific variables"
  ansible.builtin.include_vars:
    file: "{{ hostvars[inventory_hostname]['ansible_facts']['os_family'] +
      '.yml' }}"
- name: "unbound | Set facts about unbound role"
  ansible.builtin.set_fact:
    unbound_restart_method: "{{ lookup('ansible.builtin.vars', 'unbound') |
      community.general.json_query('[].restart_method | [0]') }}"
    unbound_package_state: "{{ lookup('ansible.builtin.vars', 'unbound') |
      community.general.json_query('[].package_state | [0]') }}"
    unbound_root_hints_src: "{{ lookup('ansible.builtin.vars', 'unbound') |
      community.general.json_query('[].root_hints_src | [0]') }}"
    unbound_root_hints_dst: "{{ lookup('ansible.builtin.vars', 'unbound') |
      community.general.json_query('[].root_hints_dst | [0]') }}"
    unbound_download_root_hints: "{{ lookup('ansible.builtin.vars', 'unbound') |
      community.general.json_query('[].download_root_hints | [0]') }}"
    unbound_control_setup_dst: "{{ lookup('ansible.builtin.vars', 'unbound') |
      community.general.json_query('[].control_setup_dst | [0]') }}"
    unbound_settings: "{{ lookup('ansible.builtin.vars', 'unbound') |
      community.general.json_query('[].settings[]') }}"
  when:
    - "lookup('ansible.builtin.vars', 'unbound', default='')
      not in ['', [], '[]', None]"
- name: "unbound | Assert that unbound package state in valid value"
  ansible.builtin.assert:
    that:
      - "lookup('ansible.builtin.vars', 'unbound_package_state') in
        ['present', 'latest']"
    fail_msg: "{{ 'package_state must be in `present` or `latest`,
      current is: ' + lookup('ansible.builtin.vars',
      'unbound_package_state') }}"
    quiet: "true"
  when:
    - "lookup('ansible.builtin.vars', 'unbound_package_state',
      default='') not in ['', [], '[]', None, 'present', 'latest']"
- name: "unbound | Set package state to 'present' cause value is not defined"
  ansible.builtin.set_fact:
    unbound_package_state: "present"
  when:
    - "lookup('ansible.builtin.vars', 'unbound_package_state',
      default='') in ['', [], '[]', None]"
- name: "unbound | Assert that restart method variable have proper value"
  ansible.builtin.assert:
    that:
      - "lookup('ansible.builtin.vars', 'unbound_restart_method',
        default='') in ['reload', 'restart']"
    fail_msg: "unbound restart method must be in 'reload' or 'restart'"
    quiet: "true"
  when:
    - "lookup('ansible.builtin.vars', 'unbound_restart_method',
      default='') not in ['', [], '[]', None, 'reload', 'restart']"
- name: "unbound | Set service restart method when restart method is defined"
  ansible.builtin.set_fact:
    unbound_restart_cmd: "{{ lookup('ansible.builtin.vars',
      'unbound_restart_method') + 'ed' }}"
  when:
    - "lookup('ansible.builtin.vars', 'unbound_restart_method',
      default='') in ['reload', 'restart']"
- name: "unbound | Set service restart method to SIGHUP when restart method
    is not defined"
  ansible.builtin.set_fact:
    unbound_restart_cmd: "reloaded"
  when:
    - "lookup('ansible.builtin.vars', 'unbound_restart_method',
      default='') in ['', [], '[]', None]"
- name: "unbound | Assert that root hints state in valid value"
  ansible.builtin.assert:
    that:
      - "lookup('ansible.builtin.vars', 'unbound_download_root_hints') in [true,
        false, 'true', 'false', 'always']"
    fail_msg: "'download_root_hints' must be in 'true', 'false' or 'always'"
    quiet: "true"
  when:
    - "lookup('ansible.builtin.vars', 'unbound_download_root_hints',
      default='') not in ['', [], '[]', None]"
- name: "unbound | Set service root hints state when state is not defined"
  ansible.builtin.set_fact:
    unbound_download_root_hints: "true"
  when:
    - "lookup('ansible.builtin.vars', 'unbound_download_root_hints',
      default='') in ['', [], '[]', None]"
- name: "unbound | Set root hints url when src is not defined"
  ansible.builtin.set_fact:
    unbound_root_hints_src: "https://www.internic.net/domain/named.cache"
  when:
    - "lookup('ansible.builtin.vars', 'unbound_root_hints_src',
      default='') in ['', [], '[]', None]"
- name: "unbound | Assert that root hints value is url"
  ansible.builtin.assert:
    that:
      - "lookup('ansible.builtin.vars', 'unbound_root_hints_src') is
        ansible.builtin.url()"
    fail_msg: "url not found in 'root_hints_src'"
    quiet: "true"
  when:
    - "lookup('ansible.builtin.vars', 'unbound_download_root_hints',
      default='') in [true, 'true', 'always']"
- name: "unbound | Find unbound-control certificates"
  ansible.builtin.find:
    paths: "{{ lookup('ansible.builtin.vars', 'unbound_control_setup_dst') }}"
    patterns: "unbound_control.pem"
    recurse: "no"
    file_type: "file"
  register: "unbound_control_find_result"
  when:
    - "lookup('ansible.builtin.vars', 'unbound', default='')
      not in ['', [], '[]', None]"
    - "lookup('ansible.builtin.vars', 'unbound') |
       community.general.json_query(lookup('ansible.builtin.vars',
      'unbound_control_setup', default='')) == 'true'"
  vars:
    unbound_control_setup: "[] | map(&control_setup || 'false', @) | [0]"
- name: "unbound | Stat root hints"
  ansible.builtin.stat:
    path: "{{ lookup('ansible.builtin.vars', 'unbound_root_hints_dst') }}"
  register: "unbound_root_hints_stat"
  when:
    - "lookup('ansible.builtin.vars', 'unbound_root_hints_dst',
      default='') not in ['', [], '[]', None]"
