---
- name: "unbound | Reload unbound daemon"
  listen: "Reload unbound daemon"
  ansible.builtin.systemd:
    name: "{{ lookup('ansible.builtin.vars', 'unbound_service') }}"
    state: "{{ lookup('ansible.builtin.vars', 'unbound_restart_cmd') }}"
  when:
    - "lookup('ansible.builtin.vars', 'unbound', default='')
      not in ['', [], '[]', None]"
    - "lookup('ansible.builtin.vars', 'unbound') |
       community.general.json_query(lookup('ansible.builtin.vars',
      'unbound_restart', default='')) == 'true'"
  vars:
    unbound_restart: "[] | map(&restart || 'false', @) | [0]"
